# Generated by Django 3.0.7 on 2020-11-23 15:21

from django.db import migrations, models
import django.db.models.deletion
import session_api.generators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='session_client_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(db_index=True, default=session_api.generators.generate_client_id, max_length=100, unique=True)),
                ('client_secret', models.CharField(db_index=True, default=session_api.generators.generate_client_id, max_length=100, unique=True)),
                ('activate', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('access_token', models.CharField(max_length=100, unique=True)),
                ('refresh_token', models.CharField(max_length=100, unique=True)),
                ('expiry_date', models.DateTimeField()),
                ('refresh_token_expiry', models.DateTimeField()),
                ('expired', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('session_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='session_data_client', serialize=False, to='session_api.session_client_data')),
            ],
        ),
    ]
